#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACAAE_WCFService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SACAAEDB")]
	public partial class SACAAEdbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertProfesore(Profesore instance);
    partial void UpdateProfesore(Profesore instance);
    partial void DeleteProfesore(Profesore instance);
    partial void InsertProyectosXProfesor(ProyectosXProfesor instance);
    partial void UpdateProyectosXProfesor(ProyectosXProfesor instance);
    partial void DeleteProyectosXProfesor(ProyectosXProfesor instance);
    partial void InsertProyecto(Proyecto instance);
    partial void UpdateProyecto(Proyecto instance);
    partial void DeleteProyecto(Proyecto instance);
    partial void InsertHorario(Horario instance);
    partial void UpdateHorario(Horario instance);
    partial void DeleteHorario(Horario instance);
    partial void InsertDia(Dia instance);
    partial void UpdateDia(Dia instance);
    partial void DeleteDia(Dia instance);
    partial void InsertEstado(Estado instance);
    partial void UpdateEstado(Estado instance);
    partial void DeleteEstado(Estado instance);
    partial void InsertComisione(Comisione instance);
    partial void UpdateComisione(Comisione instance);
    partial void DeleteComisione(Comisione instance);
    partial void InsertComisionesXProfesor(ComisionesXProfesor instance);
    partial void UpdateComisionesXProfesor(ComisionesXProfesor instance);
    partial void DeleteComisionesXProfesor(ComisionesXProfesor instance);
    #endregion
		
		public SACAAEdbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SACAAEDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SACAAEdbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SACAAEdbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SACAAEdbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SACAAEdbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Profesore> Profesores
		{
			get
			{
				return this.GetTable<Profesore>();
			}
		}
		
		public System.Data.Linq.Table<ProyectosXProfesor> ProyectosXProfesors
		{
			get
			{
				return this.GetTable<ProyectosXProfesor>();
			}
		}
		
		public System.Data.Linq.Table<Proyecto> Proyectos
		{
			get
			{
				return this.GetTable<Proyecto>();
			}
		}
		
		public System.Data.Linq.Table<Horario> Horarios
		{
			get
			{
				return this.GetTable<Horario>();
			}
		}
		
		public System.Data.Linq.Table<Dia> Dias
		{
			get
			{
				return this.GetTable<Dia>();
			}
		}
		
		public System.Data.Linq.Table<Estado> Estados
		{
			get
			{
				return this.GetTable<Estado>();
			}
		}
		
		public System.Data.Linq.Table<Comisione> Comisiones
		{
			get
			{
				return this.GetTable<Comisione>();
			}
		}
		
		public System.Data.Linq.Table<ComisionesXProfesor> ComisionesXProfesors
		{
			get
			{
				return this.GetTable<ComisionesXProfesor>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetProfessorsByProjectID")]
		public ISingleResult<GetProfessorsByProjectIDResult> GetProfessorsByProjectID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjectID", DbType="Int")] System.Nullable<int> projectID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), projectID);
			return ((ISingleResult<GetProfessorsByProjectIDResult>)(result.ReturnValue));
		}

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.GetProfessorsByComisionID")]
        public ISingleResult<GetProfessorsByComisionIDResult> GetProfessorsByComisionID([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "ComsionID", DbType = "Int")] System.Nullable<int> comisionID)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), comisionID);
            return ((ISingleResult<GetProfessorsByComisionIDResult>)(result.ReturnValue));
        }
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Profesores")]
	public partial class Profesore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Nombre;
		
		private string _Plaza;
		
		private int _HorasEnPropiedad;
		
		private string _Link;
		
		private int _Estado;
		
		private EntitySet<ProyectosXProfesor> _ProyectosXProfesors;
		
		private EntitySet<ComisionesXProfesor> _ComisionesXProfesors;
		
		private EntityRef<Estado> _Estado1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnPlazaChanging(string value);
    partial void OnPlazaChanged();
    partial void OnHorasEnPropiedadChanging(int value);
    partial void OnHorasEnPropiedadChanged();
    partial void OnLinkChanging(string value);
    partial void OnLinkChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    #endregion
		
		public Profesore()
		{
			this._ProyectosXProfesors = new EntitySet<ProyectosXProfesor>(new Action<ProyectosXProfesor>(this.attach_ProyectosXProfesors), new Action<ProyectosXProfesor>(this.detach_ProyectosXProfesors));
			this._ComisionesXProfesors = new EntitySet<ComisionesXProfesor>(new Action<ComisionesXProfesor>(this.attach_ComisionesXProfesors), new Action<ComisionesXProfesor>(this.detach_ComisionesXProfesors));
			this._Estado1 = default(EntityRef<Estado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Plaza", DbType="VarChar(250)")]
		public string Plaza
		{
			get
			{
				return this._Plaza;
			}
			set
			{
				if ((this._Plaza != value))
				{
					this.OnPlazaChanging(value);
					this.SendPropertyChanging();
					this._Plaza = value;
					this.SendPropertyChanged("Plaza");
					this.OnPlazaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HorasEnPropiedad", DbType="Int NOT NULL")]
		public int HorasEnPropiedad
		{
			get
			{
				return this._HorasEnPropiedad;
			}
			set
			{
				if ((this._HorasEnPropiedad != value))
				{
					this.OnHorasEnPropiedadChanging(value);
					this.SendPropertyChanging();
					this._HorasEnPropiedad = value;
					this.SendPropertyChanged("HorasEnPropiedad");
					this.OnHorasEnPropiedadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="VarChar(250)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this.OnLinkChanging(value);
					this.SendPropertyChanging();
					this._Link = value;
					this.SendPropertyChanged("Link");
					this.OnLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					if (this._Estado1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Profesore_ProyectosXProfesor", Storage="_ProyectosXProfesors", ThisKey="ID", OtherKey="Profesor")]
		public EntitySet<ProyectosXProfesor> ProyectosXProfesors
		{
			get
			{
				return this._ProyectosXProfesors;
			}
			set
			{
				this._ProyectosXProfesors.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Profesore_ComisionesXProfesor", Storage="_ComisionesXProfesors", ThisKey="ID", OtherKey="Profesor")]
		public EntitySet<ComisionesXProfesor> ComisionesXProfesors
		{
			get
			{
				return this._ComisionesXProfesors;
			}
			set
			{
				this._ComisionesXProfesors.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_Profesore", Storage="_Estado1", ThisKey="Estado", OtherKey="Id", IsForeignKey=true)]
		public Estado Estado1
		{
			get
			{
				return this._Estado1.Entity;
			}
			set
			{
				Estado previousValue = this._Estado1.Entity;
				if (((previousValue != value) 
							|| (this._Estado1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Estado1.Entity = null;
						previousValue.Profesores.Remove(this);
					}
					this._Estado1.Entity = value;
					if ((value != null))
					{
						value.Profesores.Add(this);
						this._Estado = value.Id;
					}
					else
					{
						this._Estado = default(int);
					}
					this.SendPropertyChanged("Estado1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ProyectosXProfesors(ProyectosXProfesor entity)
		{
			this.SendPropertyChanging();
			entity.Profesore = this;
		}
		
		private void detach_ProyectosXProfesors(ProyectosXProfesor entity)
		{
			this.SendPropertyChanging();
			entity.Profesore = null;
		}
		
		private void attach_ComisionesXProfesors(ComisionesXProfesor entity)
		{
			this.SendPropertyChanging();
			entity.Profesore = this;
		}
		
		private void detach_ComisionesXProfesors(ComisionesXProfesor entity)
		{
			this.SendPropertyChanging();
			entity.Profesore = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProyectosXProfesor")]
	public partial class ProyectosXProfesor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _Proyecto;
		
		private int _Profesor;
		
		private int _Periodo;
		
		private int _Horario;
		
		private EntityRef<Profesore> _Profesore;
		
		private EntityRef<Proyecto> _Proyecto1;
		
		private EntityRef<Horario> _Horario1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnProyectoChanging(int value);
    partial void OnProyectoChanged();
    partial void OnProfesorChanging(int value);
    partial void OnProfesorChanged();
    partial void OnPeriodoChanging(int value);
    partial void OnPeriodoChanged();
    partial void OnHorarioChanging(int value);
    partial void OnHorarioChanged();
    #endregion
		
		public ProyectosXProfesor()
		{
			this._Profesore = default(EntityRef<Profesore>);
			this._Proyecto1 = default(EntityRef<Proyecto>);
			this._Horario1 = default(EntityRef<Horario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proyecto", DbType="Int NOT NULL")]
		public int Proyecto
		{
			get
			{
				return this._Proyecto;
			}
			set
			{
				if ((this._Proyecto != value))
				{
					if (this._Proyecto1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProyectoChanging(value);
					this.SendPropertyChanging();
					this._Proyecto = value;
					this.SendPropertyChanged("Proyecto");
					this.OnProyectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profesor", DbType="Int NOT NULL")]
		public int Profesor
		{
			get
			{
				return this._Profesor;
			}
			set
			{
				if ((this._Profesor != value))
				{
					if (this._Profesore.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProfesorChanging(value);
					this.SendPropertyChanging();
					this._Profesor = value;
					this.SendPropertyChanged("Profesor");
					this.OnProfesorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Periodo", DbType="Int NOT NULL")]
		public int Periodo
		{
			get
			{
				return this._Periodo;
			}
			set
			{
				if ((this._Periodo != value))
				{
					this.OnPeriodoChanging(value);
					this.SendPropertyChanging();
					this._Periodo = value;
					this.SendPropertyChanged("Periodo");
					this.OnPeriodoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Horario", DbType="Int NOT NULL")]
		public int Horario
		{
			get
			{
				return this._Horario;
			}
			set
			{
				if ((this._Horario != value))
				{
					if (this._Horario1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHorarioChanging(value);
					this.SendPropertyChanging();
					this._Horario = value;
					this.SendPropertyChanged("Horario");
					this.OnHorarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Profesore_ProyectosXProfesor", Storage="_Profesore", ThisKey="Profesor", OtherKey="ID", IsForeignKey=true)]
		public Profesore Profesore
		{
			get
			{
				return this._Profesore.Entity;
			}
			set
			{
				Profesore previousValue = this._Profesore.Entity;
				if (((previousValue != value) 
							|| (this._Profesore.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Profesore.Entity = null;
						previousValue.ProyectosXProfesors.Remove(this);
					}
					this._Profesore.Entity = value;
					if ((value != null))
					{
						value.ProyectosXProfesors.Add(this);
						this._Profesor = value.ID;
					}
					else
					{
						this._Profesor = default(int);
					}
					this.SendPropertyChanged("Profesore");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proyecto_ProyectosXProfesor", Storage="_Proyecto1", ThisKey="Proyecto", OtherKey="ID", IsForeignKey=true)]
		public Proyecto Proyecto1
		{
			get
			{
				return this._Proyecto1.Entity;
			}
			set
			{
				Proyecto previousValue = this._Proyecto1.Entity;
				if (((previousValue != value) 
							|| (this._Proyecto1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Proyecto1.Entity = null;
						previousValue.ProyectosXProfesors.Remove(this);
					}
					this._Proyecto1.Entity = value;
					if ((value != null))
					{
						value.ProyectosXProfesors.Add(this);
						this._Proyecto = value.ID;
					}
					else
					{
						this._Proyecto = default(int);
					}
					this.SendPropertyChanged("Proyecto1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Horario_ProyectosXProfesor", Storage="_Horario1", ThisKey="Horario", OtherKey="Id", IsForeignKey=true)]
		public Horario Horario1
		{
			get
			{
				return this._Horario1.Entity;
			}
			set
			{
				Horario previousValue = this._Horario1.Entity;
				if (((previousValue != value) 
							|| (this._Horario1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Horario1.Entity = null;
						previousValue.ProyectosXProfesors.Remove(this);
					}
					this._Horario1.Entity = value;
					if ((value != null))
					{
						value.ProyectosXProfesors.Add(this);
						this._Horario = value.Id;
					}
					else
					{
						this._Horario = default(int);
					}
					this.SendPropertyChanged("Horario1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Proyectos")]
	public partial class Proyecto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Nombre;
		
		private System.Nullable<System.DateTime> _Inicio;
		
		private System.Nullable<System.DateTime> _Fin;
		
		private int _Estado;
		
		private string _Link;
		
		private EntitySet<ProyectosXProfesor> _ProyectosXProfesors;
		
		private EntityRef<Estado> _Estado1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnInicioChanging(System.Nullable<System.DateTime> value);
    partial void OnInicioChanged();
    partial void OnFinChanging(System.Nullable<System.DateTime> value);
    partial void OnFinChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    partial void OnLinkChanging(string value);
    partial void OnLinkChanged();
    #endregion
		
		public Proyecto()
		{
			this._ProyectosXProfesors = new EntitySet<ProyectosXProfesor>(new Action<ProyectosXProfesor>(this.attach_ProyectosXProfesors), new Action<ProyectosXProfesor>(this.detach_ProyectosXProfesors));
			this._Estado1 = default(EntityRef<Estado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inicio", DbType="DateTime")]
		public System.Nullable<System.DateTime> Inicio
		{
			get
			{
				return this._Inicio;
			}
			set
			{
				if ((this._Inicio != value))
				{
					this.OnInicioChanging(value);
					this.SendPropertyChanging();
					this._Inicio = value;
					this.SendPropertyChanged("Inicio");
					this.OnInicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fin", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fin
		{
			get
			{
				return this._Fin;
			}
			set
			{
				if ((this._Fin != value))
				{
					this.OnFinChanging(value);
					this.SendPropertyChanging();
					this._Fin = value;
					this.SendPropertyChanged("Fin");
					this.OnFinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					if (this._Estado1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="VarChar(250)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this.OnLinkChanging(value);
					this.SendPropertyChanging();
					this._Link = value;
					this.SendPropertyChanged("Link");
					this.OnLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proyecto_ProyectosXProfesor", Storage="_ProyectosXProfesors", ThisKey="ID", OtherKey="Proyecto")]
		public EntitySet<ProyectosXProfesor> ProyectosXProfesors
		{
			get
			{
				return this._ProyectosXProfesors;
			}
			set
			{
				this._ProyectosXProfesors.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_Proyecto", Storage="_Estado1", ThisKey="Estado", OtherKey="Id", IsForeignKey=true)]
		public Estado Estado1
		{
			get
			{
				return this._Estado1.Entity;
			}
			set
			{
				Estado previousValue = this._Estado1.Entity;
				if (((previousValue != value) 
							|| (this._Estado1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Estado1.Entity = null;
						previousValue.Proyectos.Remove(this);
					}
					this._Estado1.Entity = value;
					if ((value != null))
					{
						value.Proyectos.Add(this);
						this._Estado = value.Id;
					}
					else
					{
						this._Estado = default(int);
					}
					this.SendPropertyChanged("Estado1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ProyectosXProfesors(ProyectosXProfesor entity)
		{
			this.SendPropertyChanging();
			entity.Proyecto1 = this;
		}
		
		private void detach_ProyectosXProfesors(ProyectosXProfesor entity)
		{
			this.SendPropertyChanging();
			entity.Proyecto1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Horario")]
	public partial class Horario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private EntitySet<ProyectosXProfesor> _ProyectosXProfesors;
		
		private EntitySet<Dia> _Dias;
		
		private EntitySet<ComisionesXProfesor> _ComisionesXProfesors;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    #endregion
		
		public Horario()
		{
			this._ProyectosXProfesors = new EntitySet<ProyectosXProfesor>(new Action<ProyectosXProfesor>(this.attach_ProyectosXProfesors), new Action<ProyectosXProfesor>(this.detach_ProyectosXProfesors));
			this._Dias = new EntitySet<Dia>(new Action<Dia>(this.attach_Dias), new Action<Dia>(this.detach_Dias));
			this._ComisionesXProfesors = new EntitySet<ComisionesXProfesor>(new Action<ComisionesXProfesor>(this.attach_ComisionesXProfesors), new Action<ComisionesXProfesor>(this.detach_ComisionesXProfesors));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Horario_ProyectosXProfesor", Storage="_ProyectosXProfesors", ThisKey="Id", OtherKey="Horario")]
		public EntitySet<ProyectosXProfesor> ProyectosXProfesors
		{
			get
			{
				return this._ProyectosXProfesors;
			}
			set
			{
				this._ProyectosXProfesors.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Horario_Dia", Storage="_Dias", ThisKey="Id", OtherKey="Horario")]
		public EntitySet<Dia> Dias
		{
			get
			{
				return this._Dias;
			}
			set
			{
				this._Dias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Horario_ComisionesXProfesor", Storage="_ComisionesXProfesors", ThisKey="Id", OtherKey="Horario")]
		public EntitySet<ComisionesXProfesor> ComisionesXProfesors
		{
			get
			{
				return this._ComisionesXProfesors;
			}
			set
			{
				this._ComisionesXProfesors.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ProyectosXProfesors(ProyectosXProfesor entity)
		{
			this.SendPropertyChanging();
			entity.Horario1 = this;
		}
		
		private void detach_ProyectosXProfesors(ProyectosXProfesor entity)
		{
			this.SendPropertyChanging();
			entity.Horario1 = null;
		}
		
		private void attach_Dias(Dia entity)
		{
			this.SendPropertyChanging();
			entity.Horario1 = this;
		}
		
		private void detach_Dias(Dia entity)
		{
			this.SendPropertyChanging();
			entity.Horario1 = null;
		}
		
		private void attach_ComisionesXProfesors(ComisionesXProfesor entity)
		{
			this.SendPropertyChanging();
			entity.Horario1 = this;
		}
		
		private void detach_ComisionesXProfesors(ComisionesXProfesor entity)
		{
			this.SendPropertyChanging();
			entity.Horario1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dia")]
	public partial class Dia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Dia1;
		
		private int _Horario;
		
		private System.Nullable<int> _Hora_Inicio;
		
		private System.Nullable<int> _Hora_Fin;
		
		private EntityRef<Horario> _Horario1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDia1Changing(string value);
    partial void OnDia1Changed();
    partial void OnHorarioChanging(int value);
    partial void OnHorarioChanged();
    partial void OnHora_InicioChanging(System.Nullable<int> value);
    partial void OnHora_InicioChanged();
    partial void OnHora_FinChanging(System.Nullable<int> value);
    partial void OnHora_FinChanged();
    #endregion
		
		public Dia()
		{
			this._Horario1 = default(EntityRef<Horario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Dia", Storage="_Dia1", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Dia1
		{
			get
			{
				return this._Dia1;
			}
			set
			{
				if ((this._Dia1 != value))
				{
					this.OnDia1Changing(value);
					this.SendPropertyChanging();
					this._Dia1 = value;
					this.SendPropertyChanged("Dia1");
					this.OnDia1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Horario", DbType="Int NOT NULL")]
		public int Horario
		{
			get
			{
				return this._Horario;
			}
			set
			{
				if ((this._Horario != value))
				{
					if (this._Horario1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHorarioChanging(value);
					this.SendPropertyChanging();
					this._Horario = value;
					this.SendPropertyChanged("Horario");
					this.OnHorarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hora_Inicio", DbType="Int")]
		public System.Nullable<int> Hora_Inicio
		{
			get
			{
				return this._Hora_Inicio;
			}
			set
			{
				if ((this._Hora_Inicio != value))
				{
					this.OnHora_InicioChanging(value);
					this.SendPropertyChanging();
					this._Hora_Inicio = value;
					this.SendPropertyChanged("Hora_Inicio");
					this.OnHora_InicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hora_Fin", DbType="Int")]
		public System.Nullable<int> Hora_Fin
		{
			get
			{
				return this._Hora_Fin;
			}
			set
			{
				if ((this._Hora_Fin != value))
				{
					this.OnHora_FinChanging(value);
					this.SendPropertyChanging();
					this._Hora_Fin = value;
					this.SendPropertyChanged("Hora_Fin");
					this.OnHora_FinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Horario_Dia", Storage="_Horario1", ThisKey="Horario", OtherKey="Id", IsForeignKey=true)]
		public Horario Horario1
		{
			get
			{
				return this._Horario1.Entity;
			}
			set
			{
				Horario previousValue = this._Horario1.Entity;
				if (((previousValue != value) 
							|| (this._Horario1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Horario1.Entity = null;
						previousValue.Dias.Remove(this);
					}
					this._Horario1.Entity = value;
					if ((value != null))
					{
						value.Dias.Add(this);
						this._Horario = value.Id;
					}
					else
					{
						this._Horario = default(int);
					}
					this.SendPropertyChanged("Horario1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estado")]
	public partial class Estado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre;
		
		private EntitySet<Profesore> _Profesores;
		
		private EntitySet<Proyecto> _Proyectos;
		
		private EntitySet<Comisione> _Comisiones;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public Estado()
		{
			this._Profesores = new EntitySet<Profesore>(new Action<Profesore>(this.attach_Profesores), new Action<Profesore>(this.detach_Profesores));
			this._Proyectos = new EntitySet<Proyecto>(new Action<Proyecto>(this.attach_Proyectos), new Action<Proyecto>(this.detach_Proyectos));
			this._Comisiones = new EntitySet<Comisione>(new Action<Comisione>(this.attach_Comisiones), new Action<Comisione>(this.detach_Comisiones));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(250)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_Profesore", Storage="_Profesores", ThisKey="Id", OtherKey="Estado")]
		public EntitySet<Profesore> Profesores
		{
			get
			{
				return this._Profesores;
			}
			set
			{
				this._Profesores.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_Proyecto", Storage="_Proyectos", ThisKey="Id", OtherKey="Estado")]
		public EntitySet<Proyecto> Proyectos
		{
			get
			{
				return this._Proyectos;
			}
			set
			{
				this._Proyectos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_Comisione", Storage="_Comisiones", ThisKey="Id", OtherKey="Estado")]
		public EntitySet<Comisione> Comisiones
		{
			get
			{
				return this._Comisiones;
			}
			set
			{
				this._Comisiones.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Profesores(Profesore entity)
		{
			this.SendPropertyChanging();
			entity.Estado1 = this;
		}
		
		private void detach_Profesores(Profesore entity)
		{
			this.SendPropertyChanging();
			entity.Estado1 = null;
		}
		
		private void attach_Proyectos(Proyecto entity)
		{
			this.SendPropertyChanging();
			entity.Estado1 = this;
		}
		
		private void detach_Proyectos(Proyecto entity)
		{
			this.SendPropertyChanging();
			entity.Estado1 = null;
		}
		
		private void attach_Comisiones(Comisione entity)
		{
			this.SendPropertyChanging();
			entity.Estado1 = this;
		}
		
		private void detach_Comisiones(Comisione entity)
		{
			this.SendPropertyChanging();
			entity.Estado1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Comisiones")]
	public partial class Comisione : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Nombre;
		
		private System.DateTime _Inicio;
		
		private System.DateTime _Fin;
		
		private int _Estado;
		
		private EntitySet<ComisionesXProfesor> _ComisionesXProfesors;
		
		private EntityRef<Estado> _Estado1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnInicioChanging(System.DateTime value);
    partial void OnInicioChanged();
    partial void OnFinChanging(System.DateTime value);
    partial void OnFinChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    #endregion
		
		public Comisione()
		{
			this._ComisionesXProfesors = new EntitySet<ComisionesXProfesor>(new Action<ComisionesXProfesor>(this.attach_ComisionesXProfesors), new Action<ComisionesXProfesor>(this.detach_ComisionesXProfesors));
			this._Estado1 = default(EntityRef<Estado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inicio", DbType="Date NOT NULL")]
		public System.DateTime Inicio
		{
			get
			{
				return this._Inicio;
			}
			set
			{
				if ((this._Inicio != value))
				{
					this.OnInicioChanging(value);
					this.SendPropertyChanging();
					this._Inicio = value;
					this.SendPropertyChanged("Inicio");
					this.OnInicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fin", DbType="Date NOT NULL")]
		public System.DateTime Fin
		{
			get
			{
				return this._Fin;
			}
			set
			{
				if ((this._Fin != value))
				{
					this.OnFinChanging(value);
					this.SendPropertyChanging();
					this._Fin = value;
					this.SendPropertyChanged("Fin");
					this.OnFinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					if (this._Estado1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Comisione_ComisionesXProfesor", Storage="_ComisionesXProfesors", ThisKey="ID", OtherKey="Comision")]
		public EntitySet<ComisionesXProfesor> ComisionesXProfesors
		{
			get
			{
				return this._ComisionesXProfesors;
			}
			set
			{
				this._ComisionesXProfesors.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_Comisione", Storage="_Estado1", ThisKey="Estado", OtherKey="Id", IsForeignKey=true)]
		public Estado Estado1
		{
			get
			{
				return this._Estado1.Entity;
			}
			set
			{
				Estado previousValue = this._Estado1.Entity;
				if (((previousValue != value) 
							|| (this._Estado1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Estado1.Entity = null;
						previousValue.Comisiones.Remove(this);
					}
					this._Estado1.Entity = value;
					if ((value != null))
					{
						value.Comisiones.Add(this);
						this._Estado = value.Id;
					}
					else
					{
						this._Estado = default(int);
					}
					this.SendPropertyChanged("Estado1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ComisionesXProfesors(ComisionesXProfesor entity)
		{
			this.SendPropertyChanging();
			entity.Comisione = this;
		}
		
		private void detach_ComisionesXProfesors(ComisionesXProfesor entity)
		{
			this.SendPropertyChanging();
			entity.Comisione = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ComisionesXProfesor")]
	public partial class ComisionesXProfesor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _Comision;
		
		private int _Profesor;
		
		private int _Periodo;
		
		private int _Horario;
		
		private EntityRef<Comisione> _Comisione;
		
		private EntityRef<Horario> _Horario1;
		
		private EntityRef<Profesore> _Profesore;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnComisionChanging(int value);
    partial void OnComisionChanged();
    partial void OnProfesorChanging(int value);
    partial void OnProfesorChanged();
    partial void OnPeriodoChanging(int value);
    partial void OnPeriodoChanged();
    partial void OnHorarioChanging(int value);
    partial void OnHorarioChanged();
    #endregion
		
		public ComisionesXProfesor()
		{
			this._Comisione = default(EntityRef<Comisione>);
			this._Horario1 = default(EntityRef<Horario>);
			this._Profesore = default(EntityRef<Profesore>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comision", DbType="Int NOT NULL")]
		public int Comision
		{
			get
			{
				return this._Comision;
			}
			set
			{
				if ((this._Comision != value))
				{
					if (this._Comisione.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnComisionChanging(value);
					this.SendPropertyChanging();
					this._Comision = value;
					this.SendPropertyChanged("Comision");
					this.OnComisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profesor", DbType="Int NOT NULL")]
		public int Profesor
		{
			get
			{
				return this._Profesor;
			}
			set
			{
				if ((this._Profesor != value))
				{
					if (this._Profesore.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProfesorChanging(value);
					this.SendPropertyChanging();
					this._Profesor = value;
					this.SendPropertyChanged("Profesor");
					this.OnProfesorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Periodo", DbType="Int NOT NULL")]
		public int Periodo
		{
			get
			{
				return this._Periodo;
			}
			set
			{
				if ((this._Periodo != value))
				{
					this.OnPeriodoChanging(value);
					this.SendPropertyChanging();
					this._Periodo = value;
					this.SendPropertyChanged("Periodo");
					this.OnPeriodoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Horario", DbType="Int NOT NULL")]
		public int Horario
		{
			get
			{
				return this._Horario;
			}
			set
			{
				if ((this._Horario != value))
				{
					if (this._Horario1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHorarioChanging(value);
					this.SendPropertyChanging();
					this._Horario = value;
					this.SendPropertyChanged("Horario");
					this.OnHorarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Comisione_ComisionesXProfesor", Storage="_Comisione", ThisKey="Comision", OtherKey="ID", IsForeignKey=true)]
		public Comisione Comisione
		{
			get
			{
				return this._Comisione.Entity;
			}
			set
			{
				Comisione previousValue = this._Comisione.Entity;
				if (((previousValue != value) 
							|| (this._Comisione.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Comisione.Entity = null;
						previousValue.ComisionesXProfesors.Remove(this);
					}
					this._Comisione.Entity = value;
					if ((value != null))
					{
						value.ComisionesXProfesors.Add(this);
						this._Comision = value.ID;
					}
					else
					{
						this._Comision = default(int);
					}
					this.SendPropertyChanged("Comisione");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Horario_ComisionesXProfesor", Storage="_Horario1", ThisKey="Horario", OtherKey="Id", IsForeignKey=true)]
		public Horario Horario1
		{
			get
			{
				return this._Horario1.Entity;
			}
			set
			{
				Horario previousValue = this._Horario1.Entity;
				if (((previousValue != value) 
							|| (this._Horario1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Horario1.Entity = null;
						previousValue.ComisionesXProfesors.Remove(this);
					}
					this._Horario1.Entity = value;
					if ((value != null))
					{
						value.ComisionesXProfesors.Add(this);
						this._Horario = value.Id;
					}
					else
					{
						this._Horario = default(int);
					}
					this.SendPropertyChanged("Horario1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Profesore_ComisionesXProfesor", Storage="_Profesore", ThisKey="Profesor", OtherKey="ID", IsForeignKey=true)]
		public Profesore Profesore
		{
			get
			{
				return this._Profesore.Entity;
			}
			set
			{
				Profesore previousValue = this._Profesore.Entity;
				if (((previousValue != value) 
							|| (this._Profesore.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Profesore.Entity = null;
						previousValue.ComisionesXProfesors.Remove(this);
					}
					this._Profesore.Entity = value;
					if ((value != null))
					{
						value.ComisionesXProfesors.Add(this);
						this._Profesor = value.ID;
					}
					else
					{
						this._Profesor = default(int);
					}
					this.SendPropertyChanged("Profesore");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetProfessorsByProjectIDResult
	{
		
		private string _Nombre;
		
		public GetProfessorsByProjectIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
	}

    public partial class GetProfessorsByComisionIDResult
    {

        private string _Nombre;

        public GetProfessorsByComisionIDResult()
        {
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Nombre", DbType = "VarChar(250) NOT NULL", CanBeNull = false)]
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                if ((this._Nombre != value))
                {
                    this._Nombre = value;
                }
            }
        }
    }
}
#pragma warning restore 1591
